matrix:
  include:
    - language: python
      python:
        - "3.6"
      cache: pip
      before_cache:
        - rm ~/.cache/pip/log/debug.log
      install: pip install --quiet --upgrade cardboardlint pylint
      script:
        # Run cardboardlinter, in case of pull requests
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            cardboardlinter --refspec $TRAVIS_BRANCH -n auto;
          fi
    - language: go
      install: go get github.com/bazelbuild/buildtools/buildifier
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            buildifier --lint=warn -r native_client
          fi
