name: build-python-wheels
on: [push]
defaults:
  run:
    shell: bash
jobs:
  build-tensorflow:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - run: pwd
      - run: ls -lh
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:tflite-base-build || true
      - run: docker pull docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:tflite-lib-build || true
      - run: docker pull docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:pybase || true
      - run: >
          docker build . -t tflite-lib-build-local --target tflite-lib-build -f ci_scripts/linux-python-wheels.dockerfile
          --cache-from=docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:tflite-lib-build
          --cache-from=docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:tflite-base-build
          --cache-from=docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:pybase
      - run: >
          docker build . -t tflite-base-build-local --target tflite-base-build -f ci_scripts/linux-python-wheels.dockerfile
      - run: >
          docker build . -t pybase-local --target pybase -f ci_scripts/linux-python-wheels.dockerfile
      - run: >
          docker tag pybase-local docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:pybase &&
          docker tag tflite-base-build-local docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:tflite-base-build &&
          docker tag tflite-lib-build-local docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:tflite-lib-build &&
          docker push --all-tags docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels
  build-py36-tf-wheel:
    runs-on: ubuntu-18.04
    needs: build-tensorflow
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:tflite-base-build || true
      - run: docker pull docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:tflite-lib-build || true
      - run: docker pull docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:pybase || true
      - run: docker pull docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:py36 || true
      - run: docker pull docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:py36-artifact || true
      - run: >
          docker build . -t py36-artifact-local --target py36-artifact -f ci_scripts/linux-python-wheels.dockerfile
          --cache-from=docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:py36-artifact
          --cache-from=docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:py36
          --cache-from=docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:pybase
          --cache-from=docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:tflite-lib-build
          --cache-from=docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:tflite-base-build
      - run: >
          docker build . -t py36-local --target py36 -f ci_scripts/linux-python-wheels.dockerfile
      - run: >
          docker tag py36-artifact-local docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:py36-artifact &&
          docker tag py36-local docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels:py36 &&
          docker push --all-tags docker.pkg.github.com/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')/cache-linux-py-wheels
  # build-py37-tf-wheel:
  #   needs: build-tensorflow
  #   steps:
  #     - name: Build TF Python 3.7 wheel
  #       run: .github/scripts/build-python-wheel.sh 3.7
  # build-py38-tf-wheel:
  #   needs: build-tensorflow
  #   steps:
  #     - name: Build TF Python 3.8 wheel
  #       run: .github/scripts/build-python-wheel.sh 3.8
  # build-py39-tf-wheel:
  #   needs: build-tensorflow
  #   steps:
  #     - name: Build TF Python 3.9 wheel
  #       run: .github/scripts/build-python-wheel.sh 3.9
  # # build-tensorflow-tflite:
  # #   steps:
  # #     - name: Build TensorFlow (TFLite)
  # #       run: .github/scripts/build-tensorflow.sh --tflite
